### PR TITLE
Add proper logging

### PR DESCRIPTION
**Pull request by stefanleh**
* considered configurations -> warn
* currently processed configuration -> info
* copied resources -> info
* exceptions when resolving parent poms -> error

Only warn and error are always logged by default.
Info loggings can be seen by using --info flag of gradle.

### CODE REVIEW

**Comment by uklance** [comment]
Please see https://github.com/uklance/gradle-dependency-export/commit/036344f18a3dd2df5301cc7ffc79051a7f549caa

**Comment by stefanleh** [comment]
I'll rebase on your changes tomorrow.

**Comment by stefanleh** [comment]
Hi Lance, i've used tabs instead of spaces now for formatting as i guess thats what you've used as well.
Also i've added logging for the case people try to set non resolvable configurations via the configuration methods.

**Comment by stefanleh** [comment]
Just added a proper testcase for the filtering of custom set non resolvable configurations.

**Comment by uklance** [comment]
Note, I've made the configurations collection public now so the
isResolvable check will need to move to the task action rather than the
configuration(...) methods

**Comment by stefanleh** [comment]
> Note, I've made the configurations collection public now so the isResolvable check will need to move to the task action rather than the configuration(...) methods

I've solved that topic using a custom setter method for configurations that uses the configuration method. Please have a look.

**Comment by stefanleh** [comment]
Hi Lance, did you find the time to review the PR yet?

**Comment by uklance** [comment]
Hi, I'm coding all week at work so don't tend to do much on the side on
weekdays. I'll try to have a look on the weekend

**Comment by stefanleh** [comment]
Ok, no worries.

**Comment by stefanleh** [comment]
Just updated the PR to your latest changes.

**Pull request merged**
