### PR TITLE
Update implementation

### PR DESCRIPTION
**Pull request by stefanleh**
* filtering of configurations
* catching exceptions of pom resolve logic
* copy system properties important for pom resolving to context
* update README.md
* update Gradle Wrapper to 5.2.1
* set fixed project name to avoid different named artifact

Sorry for the german comments. Will fix that in 0.3 ...

### CODE REVIEW

**Comment by uklance** [comment]
Thanks for your contribution. I'll hopefully try it out soon and push out a release for you.

Cheers, 
Lance

**Comment by uklance** [comment]
I built and published version 0.2 of this plugin to the plugin portal. Apparently it can take up to 24 hours to be approved.

**Comment by stefanleh** [comment]
Thanks. I appreciate your effort for releasing.

**Comment by uklance** [comment]
I made a couple of changes and release version 0.3

1. I removed `defaultConfigurations.findAll { it.canBeResolved  }` logic. If you need a custom collection of configurations, please manually set the configurations (see readme)
2. I added a `systemProperties` Map to the task (defaults to System.getProperties()) which can be customized.

**Comment by stefanleh** [comment]
Great News. Will send a PR soon for the logging and comments in english.




von unterwegs gesendet mit Bitte um Nachsicht bei Kürze und Form







On Sun, Feb 24, 2019 at 1:59 PM +0100, "Lance" <notifications@github.com> wrote:












I made a couple of changes and release version 0.3

I removed defaultConfigurations.findAll { it.canBeResolved  } logic. If you need a custom collection of configurations, please manually set the configurations (see readme)
I added a systemProperties Map to the task (defaults to System.getProperties()) which can be customized.

**Comment by stefanleh** [comment]
I just saw that you left the defaultConfugurations handling in place. The defaults dont work with current gradle relaeses, thats the cause i added defaultConfigurations.findAll { it.canBeResolved  }. All configuraitons considered have the resolvable. The current default handling will break all the time and is therefore useless. I suggest to remove it completely and rely on propert configuration by the user.

**Comment by uklance** [comment]
The test case works perfectly with default configurations. Can you tell me
a bit more about these unresolvable configurations you have?

I'd prefer my build to fail if it can't export a dependency rather than
skipping it silently only for something else to fail building offline.

**Comment by stefanleh** [comment]
For me it was:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':mavenDependencyExport'.
> Resolving configuration 'testRuntimeOnly' directly is not allowed

Guess you dont have testRuntimeOnly in you testcase?

**Comment by uklance** [comment]
Whoops, I was wrong

https://github.com/uklance/gradle-dependency-export/blob/master/src/test/groovy/com/lazan/dependency/export/MavenDependencyExportTest.groovy#L52

The test sets a configuration which means the default logic doesn't fire

**Comment by stefanleh** [comment]
Currently i have to use:

    mavenDependencyExport {
        
        for (Configuration conf : project.buildscript.configurations.findAll{ it.canBeResolved }) {
            configuration conf
        }
        for (Configuration conf : project.configurations.findAll{ it.canBeResolved }) {
            configuration conf
        }
        
    }

to make it work.
Maybe making the configurations non private would be fine?
Then i can remove at least the foreach loops.

**Comment by uklance** [comment]
I didn't make configurations public/settable because it might get confused
with project.configurations (people often use "configurations" in a gradle
script without qualifying it)

Let me do some research on canBeResolved flag. Perhaps your logic is more
sensible.

**Comment by stefanleh** [comment]
I see following approaches:
* removing default handling and adding some hints to documentation
* filtering the defaults with the canBeResolved and add logging about which configs are considered (and also maybe which were dropped)
* removing default handling and provide an allResolvableConfigurations method which can be used in the plugin configuration in the mavenDependencyExport closure

**Comment by uklance** [comment]
Ok, looking at the javadocs

https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Configuration.html#isCanBeResolved--

"Returns true if it is allowed to query or resolve this configuration.
Defaults to true."

I'm happy to put your logic back in the default method. I agree that
showing this exclusion in the logs is a good idea.

I'm also happy to log the configuration name and also the filenames via the
Gradle logger. This would need to be in English rather than German.

**Pull request merged**
